export const urls = new Map()
  .set('Mozilla', 'https://blog.mozilla.org')
  .set('Variety', 'http://variety.com')
  .set('Bloomberg', 'https://www.bloomberg.com/professional')
  .set('The Next Web', 'https://thenextweb.com')
  .set('Observer', 'http://observer.com')
  .set('Fortune', 'http://fortune.com')
  .set('Time', 'http://time.com')
  .set('SI National Museum of African Art', 'https://africa.si.edu')
