export const urls = new Map()
  .set('Mozilla', 'https://blog.mozilla.org')
  .set('Variety', 'https://variety.com')
  .set('Bloomberg', 'https://www.bloomberg.com/professional')
  .set('The Next Web', 'https://thenextweb.com')
  .set('Observer', 'https://observer.com')
  .set('Fortune', 'https://fortune.com')
  .set('Time', 'http://time.com')
  .set('SI National Museum of African Art', 'https://africa.si.edu')
  .set('VentureBeat', 'https://venturebeat.com')
  // Blockchain news
  .set('CoinDesk', 'https://www.coindesk.com')
  .set('NewsBTC', 'https://www.newsbtc.com')
  .set('The Merkle', 'https://themerkle.com')
  .set('TrustNodes', 'https://www.trustnodes.com')
